name: Publish Any Commit
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install corepack with bypass
        run: npm i -g --force corepack && corepack enable

      - name: Install dependencies
        run: npm install --no-frozen-lockfile

      - name: Build it
        run: npm run build

      - name: Publish the package
        run: npx pkg-pr-new publish