name: Publish Any Commit
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: npm/action-setup@v4
        with:
          version: 10

      - name: Install corepack with bypass
        run: npx i -g --force corepack && corepack enable

      - name: Install dependencies
        run: npx install

      - name: Build it
        run: npx build

      - name: Publish the package
        run: npx pkg-pr-new publish